### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by zacadelman** [USEPA/AMET#12]
- Update User's Guide TOC once the content is near final
- Clean up headings in the user's guide to render correctly in Git Hub
- Add AMET Met instructions in user's guide
- Add Installation Guide from UNC

**Comment by zacadelman** [comment]
Internal Link example:

```
Anchor: <a id="Figure4-1"></a>
Reference to an anchor: [Figure 4-1](#Figure4-1)
```

Where the reference renders as the link Figure 4-1
The syntax to use in the link to the anchor is #anchorName

**Comment by zacadelman** [comment]
Add documentation on AQ obs data format for bringing in your own data to the system.

**Comment by zacadelman** [comment]
Image example:

```
<a id="Figure4-2"></a>
![](./images/Figure4-2.png "Figure4-2.png")
```

**Comment by wkappel** [comment]
I've finished updating the User's Guide with my content. I added links to images and anchors. Rob, you can start editing the User's Guide now.

**Comment by wkappel** [comment]
I think this issue is pretty much closed now.
