### ISSUE TITLE
2015/16 Obs Data

### ISSUE THREAD

**Issue by zacadelman** [USEPA/AMET#25]
Need to add Obs data for 2015/16 to the CMAS data clearinghouse.  Currently we have data for 2001-2014: https://drive.google.com/drive/folders/0B2kjxCwKICxUZ3ZyNEVld2F6bHc

**Comment by wkappel** [comment]
I have the 2015 data ready, but the 2016 data are still incomplete. I think we should just hold off on including the 2016 data until we have a more complete data set.

**Comment by wkappel** [comment]
I checked on the 2016 data and it's indeed incomplete. So, I'll provide the 2015 data and hold off on the 2016 data until a later date.
