### ISSUE TITLE
Version 1.3 Final Testing

### ISSUE THREAD

**Issue by zacadelman** [USEPA/AMET#31]
The documentation for v1.3 (Section 6.2) refers to a combine subdirectory under $AMETBASE/scripts\_db/aqExample.  Is this directory missing in the installation or should I omit this reference in the documentation?

**Comment by wkappel** [comment]
Yeah, this is a good question. I never really tackled that section. Now that we provide combine with the CMAQ release and scripts to do combine, I wonder if I should just rewrite this section and refer to the CMAQ documentation for combine. Let me think about that and come up with a solution today.

**Comment by wkappel** [comment]
Alright, I modified that section to point the user to the CMAQ documentation for running combine. I think that makes the most sense. In the near future, we're going to provide a master post-processing script that will help users run combine and site compare (and AMET if they have that installed). I don't think we need to rehash that in the AMET documentation. So no, we don't need a combine directory.
