### ISSUE TITLE
Update AQ_Soccerplot.R

### ISSUE THREAD

**Issue by zacadelman** [USEPA/AMET#34]
Minor change to AQ_Soccerplot.R to work with the new credentials:

Change root_login and root_pass to amet_login and amet_pass in the following two lines:

```
mysql <- list(login=root_login, passwd=root_pass, server=mysql_server, dbase=dbase, maxrec=1000000)
con             <- dbConnect(MySQL(),user=root_login,password=root_pass,dbname=dbase,host=mysql_server)
```

**Comment by wkappel** [comment]
Thanks for catching this Zac. I actually need to remove those lines entirely from that script. The "mysql" variable is defined in the AQ_Misc_Functions.R file that is sourced. I just forgot to remove these lines. I'm going to push the new code up. I feel confident it will work, but if you get a chance to test it, great.

**Comment by wkappel** [comment]
I think we should be good on this issue. Closing it.
