### ISSUE TITLE
site_metadata_files

### ISSUE THREAD

**Issue by zacadelman** [USEPA/AMET#7]
Add $AMETBASE/obs/site_metadata_files to the distribution rep.

**Comment by zacadelman** [comment]
Also need to add $AMETBASE/obs/AQ/NA_Data to the repo

**Comment by wkappel** [comment]
I think we'll need to distribute these files in a tarball along with the model data. I'm envisioning a tar file that we can point the user to that they can then download and untar in their AMET base directory and it will populate the appropriate sub-directories with the model data, obs data, and site metadata files.

**Comment by wkappel** [comment]
Will provide a tarball with required obs, model and site files for both the AQ and Met that users can download and extract into their existing AMET directory.
