### ISSUE TITLE
Cannot build bldoverlay, sitecmp, and sitecmp_dailyo3.

### ISSUE THREAD

**Issue by tfriesner** [USEPA/AMET#73]
According to the AMET_Install_Guide_v14b under the section Install AMET Source Code and Tier 3 Software there should be a src directory containing the programs bldoverlay, sitecmp, and sitecmp_dailyo3.  The src directory appears to be missing in the 14b release.  There is a directory called tools_src which seems to have the source for these programs and the config.amet file.  However, they are missing any make files to build bldoverlay, sitecmp, and sitecmp_dailyo3.

**Comment by tfriesner** [comment]
The bldit* scripts are looking for a script called config_cmaq.csh in my AMET root directory which is not there.  I did a search for this file and could not find it.  Am I missing a step that creates config_cmaq.csh?

Here is the "error" I am getting:
./config_cmaq.csh: No such file or directory.

Your help in this is greatly appreciated!

**Comment by wkappel** [comment]
I think that the bldit script should be sourcing config.amet and not config_cmaq.csh. Liz, can you confirm that is the case. Also, I do see now that combine is included in the tools_src directory. Not sure why I thought it wasn't.

**Comment by lizadams** [comment]
It looks like the bldit script is looking for the config_cmaq.csh

#> Source the config.cmaq file to set the build environment
 cd ../../..
 source ./config_cmaq.csh

I don't see a config.csh script in the AMET repository.
Do you have one.

When I tried linking the config_cmaq.csh file from the CMAQ directory and then running bldit, it failed.

Liz

________________________________

**Comment by wkappel** [comment]
The config script I would have is the one that comes with the CMAQ code, but that is ultimately created by the CMAQ bldit project script. Seems too complicated to apply that method here.

Christian and I agreed the simplest solution would be to include make files and let users update the necessary IOAPI and NetCDF paths in there and just run make. I'll work on doing that and push an update on Monday. Then I'll update the documentation accordingly. 

Sorry for the confusion Ted. Be on the lookout for some updates early next week.

**Comment by wkappel** [comment]
I'm assuming this issue has been resolved, therefore I will close this issue.

Wyat
