### ISSUE TITLE
AMET on HPC cluster with no MySQL

### ISSUE THREAD

**Issue by lisalenorelowe** [USEPA/AMET#76]
Hi,
Is there an option to run AMET without having a MySQL connection, maybe by somehow using SQLite when compiling?
If not, any plans in the future to implement this?
Thanks,
Lisa

**Comment by wkappel** [comment]
Hi Lisa,

Please see my response to the same question from someone else on CMASCENTER listsever. I've provided the link to the relevant topic below. Let me know if that answers your question or not.

https://forum.cmascenter.org/t/how-to-use-amet-without-mysql/889

Wyat

**Comment by lisalenorelowe** [comment]
Great, thanks!
