### ISSUE TITLE
AQ Batch Scripts

### ISSUE THREAD

**Issue by zacadelman** [USEPA/AMET#9]
There are settings missing from AMET_batch.input that result in failure of the scatter density plots. Add these fields to the release script:

density_zlim<-NULL
num_dens_bins<-NULL
bin_by_mod<-""

The new run_AMET_batch.csh script is looking for:
setenv AMETRINPUT $AMETBASE/scripts_analysis/aqExample/input_files/AMET_batch.R

I'm only seeing AMET_batch.input in the input_files directory. It seems to work to use the *.input file.  Is this just a type in the repo distribution?

**Comment by wkappel** [comment]
I've added three missing variables to the AMET_batch.input file.

 I also renamed AMET_batch.R to AMET_batch.input to be consistent with the current run_AMET_batch.csh script.
